--WHERE절

SELECT * FROM EMPLOYEES;
SELECT FIRST_NAME, JOB_ID FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG';
SELECT * FROM EMPLOYEES WHERE SALARY >= 15000;
SELECT * FROM EMPLOYEES WHERE SALARY < 10000;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID <> 50; --같지 않음
SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'STEVEN'; --데이터는 대소문자를 구분함
SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'Steven'; --데이터는 대소문자를 구분함
SELECT * FROM EMPLOYEES WHERE HIRE_DATE = '04/01/30'; --날짜는 그냥 문자열로 찾으면 된다
SELECT * FROM EMPLOYEES WHERE HIRE_DATE <= '04/01/30'; --대소비교도 된다

--BETWEEN A AND B (이상~이하)
SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 10000 AND 15000;
SELECT * FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '03/01/01' AND '03/12/31';


--IN 연산자
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (50,60,70);
SELECT * FROM EMPLOYEES WHERE JOB_ID IN('IT_PROG', 'AD_VP');
--LIKE 연산자
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '03%'; --03으로 시작한
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '%01'; --01으로 끝난
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '%05%'; --05가 들어간
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE '_ar%'; -- _는 자리 수를 의미/ 여기선 1개니까 ar 앞에 한자리 있어야 함
SELECT * FROM EMPLOYEES WHERE HIRE_DATE LIKE '___05%';

--IS NULL, IS NOT NULL
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT = NULL; --NULL인 사람이 없는게 아니라 잘못 찾은것
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL;
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NOT NULL;

--AND, OR / AND 가 OR보다 연산순위가 빠르다
SELECT * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG' OR SALARY >= 5000; --둘 중 하나만 만족해도 나옴
SELECT * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG' AND SALARY >= 5000; -- 둘 다 만족해야 나옴
SELECT * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG' OR JOB_ID = 'FI_MGR' AND SALARY >= 5000; --AND가 먼저 동작
SELECT * FROM EMPLOYEES WHERE (JOB_ID = 'IT_PROG' OR JOB_ID = 'FI_MGR') AND SALARY >= 5000; --OR가 먼저 동작하도록 ()써주기

--NOT 부정의 의미
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID NOT IN(50,60,70); --50,60,70이 아닌 데이터 찾기
SELECT * FROM EMPLOYEES WHERE JOB_ID NOT LIKE '%IT%'; --IT가 없는 데이터 찾기

--------------------------------------------------------------------------------------------

--ORDER BY구문
SELECT * FROM EMPLOYEES ORDER BY SALARY; -- ASC가 디폴트
SELECT * FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT * FROM EMPLOYEES ORDER BY DEPARTMENT_ID, SALARY DESC; --DEPARTMENT_ID 기준으로 먼저 정렬, 그 안에서 SALARY기준으로 정렬(근데 DESC니까 내림차순으로

SELECT FIRST_NAME, SALARY*12 AS 연봉 FROM EMPLOYEES ORDER BY 연봉 DESC; --엘리어스를 정렬에서 사용할 수 있다
SELECT FIRST_NAME, SALARY*12 AS 연봉 FROM EMPLOYEES WHERE 연봉 >= 10000; --안되는 거임 WHERE 사용 X

SELECT FIRST_NAME, SALARY, DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID = 50 ORDER BY FIRST_NAME;











