CREATE TABLE USERS(
    EMAIL VARCHAR2(30),
    NAME VARCHAR2(30) NOT NULL,
    PW VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(30),
    GENDER CHAR(1),
    SNS_YN CHAR(1),
    REGDATE DATE DEFAULT SYSDATE
);
ALTER TABLE USERS ADD CONSTRAINT EMAIL_PK PRIMARY KEY (EMAIL);
ALTER TABLE USERS ADD CONSTRAINT GENDER_CK CHECK (GENDER IN ('M','F'));
ALTER TABLE USERS ADD CONSTRAINT SNS_CK CHECK(SNS_YN IN ('Y', 'N'));

DROP TABLE USERS;

SELECT * FROM USERS;

UPDATE USERS SET NAME = '이순신', PHONE = '010-9874-6541', GENDER ='F', SNS_YN ='Y'  WHERE EMAIL = 'qwer@naver.com';
			
            
DLELTE FROM USERS WHERE EMAIL = ?            
SELECT * FROM USERS;